#include "game.h"

// Inizializzazione del contenitore delle stanze con i relativi oggetti
room container[MAX_ROOM_NUMBER] = {
    {
        .room_id = 0,
        .name = "Fuga dal passato",
        .description = "Ti risvegli senza ricordi e con una forte emicrania in una stanza che non riesci a riconoscere. La camera sembra poveramente arredata e riesci a sentire un forte rumore provenire dall'esterno. Accanto a te è presente un ++comodino++ e una ++finestra++, mentre poco distanti sono presenti una ++scrivania++, un ++armadio++ e la ++porta++ della camera.", 
        .token = 4,
        .inventory_size = 5,
        .time = 1200, 
        .loc = {
            {
                .name = "comodino",
                .description = "Un comodino di legno di piccole dimensioni, sopra di esso sono presenti un **calendario** in legno e una **candela** spenta.",
            },
            {
                .name = "finestra",
                .description = "Una finestra con delle sbarre di ferro, troppo strette per lasciarti uscire. Dalla finestra riesci a vedere un **piccione** poco lontano con una strana targhetta di legno sulla zampa e un incendio che divampa poco distante.",
            },
            {
                .name = "scrivania",
                .description = "Una scrivania in legno e sopra di essa un **giornale**, un **cubo** di legno chiuso da un lucchetto e degli **avanzi** di un probabile scorso pasto. Noti, inoltre, sul soffitto sopra la scrivania una **videocamera**.",
            },
            {
                .name = "armadio",
                .description = "Un armadio in legno con due scaffali: nel primo, tra i vestiti è presente una giacca, che ha nella tasca laterale dei **fiammiferi**, mentre nell'altro scaffale è presente una **cassaforte** in metallo.",
            },
            {
                .name = "porta",
                .description = "Una vecchia porta di metallo, su cui è presente uno **spioncino**, un **poster** con un'immagine del celebre libro 1984 e una **fessura** in cui riesci ad inserire la mano. La porta presenta dei segni di manomissione recenti.",
            },
        },
        .obj = {
            {
                .name = "calendario",
                .description = "Un vecchissimo calendario di legno, collegato ad un'infinità di cavi che escono dal muro. Sembra si possano inserire degli oggetti rettangolari in legno in quattro alloggiamenti, ma al momento tutti e quattro gli alloggiamenti sono liberi.",
                .takeable = false,
                .visible = true,
                .riddle = true,
                .rdl_description = "",
                .rdl_answer = "",
                .token = false,
                .new_description = "",
                .description_after_usage_alone = "Provi a forzare il calendario, ma non ci riesci.",
                .description_after_usage = "",
                .used_with = "",
                .item_unlocked = {0, 0, 0},
            },
            {
                .name = "candela",
                .description = "Una candela abbastanza spessa e colorata di rosso. Si vede un pezzetto di carta sporgere lateralmente.",
                .takeable = true,
                .visible = true,
                .riddle = true,
                .rdl_description = "",
                .rdl_answer = "",
                .token = false,
                .new_description = "La cera della candela è sciolta e il pezzetto di **carta** è ora molto più visibile.",
                .description_after_usage_alone = "Provi a togliere il foglietto dalla candela, ma non ci riesci",
                .description_after_usage = "",
                .used_with = "",
                .item_unlocked = {2, 1, 1},
            },
            {
                .name = "carta",
                .description = "Il pezzetto di carta è una pagina di un libro, che recita «It was a bright cold day in April, and the clocks were striking thirteen. Winston Smith, his chin nuzzled into his breast in an effort to escape the vile wind... »",
                .takeable = true,
                .visible = false,
                .riddle = false,
                .rdl_description = "",
                .rdl_answer = "",
                .token = false,
                .new_description = "",
                .description_after_usage_alone = "Rileggi il foglietto, ma non sembra essere cambiato nulla.",
                .description_after_usage = "",
                .used_with = "",
                .item_unlocked = {2, 2, 2},
            },
            {
                .name = "piccione",
                .description = "Un piccione viaggiatore con un collare rosso pieno di occhi disegnati in nero e una targhetta sulla zampa.",
                .takeable = false,
                .visible = true,
                .riddle = true,
                .rdl_description = "",
                .rdl_answer = "",
                .token = false,
                .new_description = "....",
                .description_after_usage_alone = "Il piccione vola via per poi tornare nello stesso punto.",
                .description_after_usage = "",
                .used_with = "",
                .item_unlocked = {4, 3, 3},
            },
            {
                .name = "targhetta(24)",
                .description = "Una targhetta rettangolare, sembra abbia la dimensione adatta per essere inserita nel calendario.",
                .takeable = true,
                .visible = false,
                .riddle = false,
                .rdl_description = "",
                .rdl_answer = "",
                .token = true,
                .new_description = "",
                .description_after_usage_alone = "Guardi la targhetta, ma non sembra essere cambiato nulla.",
                .description_after_usage = "Hai inserito la targhetta nel calendario, ora le ultime due cifre relative all'anno sono '24'.",
                .used_with = "calendario",
                .item_unlocked = {4, 4, 4},
            },
            {
                .name = "giornale",
                .description = "Il giornale presenta in alto la data '14-11-1984' e in prima pagina c'è una notizia che cattura il tuo interesse: 'Terminata con successo la sperimentazione sul viaggio nel tempo'.",
                .takeable = true,
                .visible = true,
                .riddle = false,
                .rdl_description = "",
                .rdl_answer = "",
                .token = false,
                .new_description = "",
                .description_after_usage_alone = "Rifletti sulla notizia, ma non sembra essere cambiato nulla.",
                .description_after_usage = "",
                .used_with = "",
                .item_unlocked = {5, 5, 5},
            },
            {
                .name = "cubo",
                .description = "Un cubo di legno antico con un'incisione fatta a fuoco che recita un indovinello. Il cubo è chiuso da un lucchetto.",
                .takeable = true,
                .visible = true,
                .riddle = true,
                .rdl_description = "Come si chiama il personaggio principale del libro '1984' di George Orwell?",
                .rdl_answer = "Winston",
                .token = false,
                .new_description = "Il cubo è ora aperto e all interno è presente una **targhetta(20)**.",
                .description_after_usage_alone = "Provi a forzare il cubo, ma non ci riesci.",
                .description_after_usage = "",
                .used_with = "",
                .item_unlocked = {7, 6, 6},
            },
            {
                .name = "targhetta(20)",
                .description = "Una targhetta rettangolare, sembra abbia la dimensione adatta per essere inserita nel calendario.",
                .takeable = true,
                .visible = false,
                .riddle = false,
                .rdl_description = "",
                .rdl_answer = "",
                .token = true,
                .new_description = "",
                .description_after_usage_alone = "Guardi la targhetta, ma non sembra essere cambiato nulla.",
                .description_after_usage = "Hai inserito la targhetta nel calendario, ora le prime due cifre relative all'anno sono '20'.",
                .used_with = "calendario",
                .item_unlocked = {7, 7, 7},
            },
            {
                .name = "avanzi",
                .description = "Degli avanzi di un pasto consumato di recente, sono presenti dei pezzetti di pane ai semi.",
                .takeable = true,
                .visible = true,
                .riddle = false,
                .rdl_description = "",
                .rdl_answer = "",
                .token = false,
                .new_description = "",
                .description_after_usage_alone = "Mangi un pezzetto di pane, ma non sembra essere cambiato nulla.",
                .description_after_usage = "Il piccione mangia gli avanzi dalla tua mano e dopo aver finito vola via. Sulla finestra è presente una **targhetta(24)**.",
                .used_with = "piccione",
                .item_unlocked = {8, 8, 8},
            },
            {
                .name = "videocamera",
                .description = "Una videocamera estramente moderna, che cozza con il resto della camera. Sembra, infatti, sia stata installata molto di recente.",
                .takeable = false,
                .visible = true,
                .riddle = true,
                .rdl_description = "",
                .rdl_answer = "",
                .token = false,
                .new_description = "La videocamera è spenta.",
                .description_after_usage_alone = "Provi a rompere la videocamera, ma non ci riesci.",
                .description_after_usage = "",
                .used_with = "",
                .item_unlocked = {16, 17, 9},
            },
            {
                .name = "fiammiferi",
                .description = "Un pacchetto di fiammiferi quasi nuovo.",
                .takeable = true,
                .visible = true,
                .riddle = false,
                .rdl_description = "",
                .rdl_answer = "",
                .token = false,
                .new_description = "",
                .description_after_usage_alone = "Accendi un fiammifero per farti luce, ma non sembra essere cambiato nulla.",
                .description_after_usage = "La cera si scioglie e il pezzetto di **carta** sembra ora molto semplice da prendere.",
                .used_with = "candela",
                .item_unlocked = {10, 10, 10},
            },
            {  
                .name = "cassaforte",
                .description = "Una cassaforte di materiale robusto, sembra non si possa aprire se non si conosce la combinazione.",
                .takeable = false,
                .visible = true,
                .riddle = true,
                .rdl_description = "In quale delle tre potenze mondiali è ambientato il libro '1984' di George Orwell? \n1) Oceania \n2) Eurasia \n3) Estasia",
                .rdl_answer = "1",
                .token = false,
                .new_description = "La cassaforte è ora aperta e all'interno è presente una **targhetta(11)**.",
                .description_after_usage_alone = "Provi a forzare la cassaforte, ma non ci riesci.",
                .description_after_usage = "",
                .used_with = "",
                .item_unlocked = {12, 11, 11},
            },
            {
                .name = "targhetta(11)",
                .description = "Una targhetta rettangolare, sembra abbia la dimensione adatta per essere inserita nel calendario.",
                .takeable = true,
                .visible = false,
                .riddle = false,
                .rdl_description = "",
                .rdl_answer = "",
                .token = true,
                .new_description = "",
                .description_after_usage_alone = "Guardi la targhetta, ma non sembra essere cambiato nulla.",
                .description_after_usage = "Hai inserito la targhetta nel calendario, ora le due cifre relative al mese sono '11'.",
                .used_with = "calendario",
                .item_unlocked = {12, 12, 12},
            },
            {
                .name = "spioncino",
                .description = "Dallo spioncino vedi segni due uomini: uno sembra una guardia carceraria ed è a terra sanguiante, l'altra ha un completo da soldato con un simbolo di un occhio sul busto.",
                .takeable = false,
                .visible = true,
                .riddle = false,
                .rdl_description = "",
                .rdl_answer = "",
                .token = false,
                .new_description = "",
                .description_after_usage_alone = "Provi a rompere lo spioncino per cercare una via di fuga, ma non ci riesci.",
                .description_after_usage = "",
                .used_with = "",
                .item_unlocked = {13, 13, 13},
            },
            {
                .name = "poster",
                .description = "Un poster del celebre libro '1984' di George Orwell, presenta un'immagine di un occhio ed, intorno, la celebre frase 'Il Grande Fratello ti sta guardando'. Il poster è nuovo, sembra che sia stato attaccato al muro di recente e presenta una **iscrizione** fatta a penna.",
                .takeable = true,
                .visible = true,
                .riddle = false,
                .rdl_description = "",
                .rdl_answer = "",
                .token = false,
                .new_description = "",
                .description_after_usage_alone = "Riguardi il poster, ma non sembra essere cambiato nulla.",
                .description_after_usage = "Mostri il poster alla videocamera e, subito dopo, senti un rumore provenire dalla **fessura**, che ora è aperta.",
                .used_with = "videocamera",
                .item_unlocked = {14, 14, 14},
            },
            {
                .name = "iscrizione",
                .description = "Una iscrizione fatta a penna rossa che recita: 'La Fratellanza è arrivata, dimostra la tua lealtà e sarai libero'. ",
                .takeable = false,
                .visible = true,
                .riddle = false,
                .rdl_description = "",
                .rdl_answer = "",
                .token = false,
                .new_description = "",
                .description_after_usage_alone = "Rileggi l'iscrizione in cerca di indizi, ma non sembra essere cambiato nulla.",
                .description_after_usage = "",
                .used_with = "",
                .item_unlocked = {15, 15, 15},
            },
            {  
                .name = "fessura",
                .description = "Una fessura simile a quella che si vede nelle celle d'isolamento delle prigioni, al momento sembra chiusa.",
                .takeable = false,
                .visible = true,
                .riddle = true,
                .rdl_description = "",
                .rdl_answer = "",
                .token = false,
                .new_description = "La fessura è ora aperta e all'interno è presente una **targhetta(14)**.",
                .description_after_usage_alone = "Provi a forzare la fessura con le mani, ma non ci riesci.",
                .description_after_usage = "",
                .used_with = "",
                .item_unlocked = {16, 16, 16},
            }, 
            {
                .name = "targhetta(14)",
                .description = "Una targhetta rettangolare, sembra abbia la dimensione adatta per essere inserita nel calendario.",
                .takeable = true,
                .visible = false,
                .riddle = false,
                .rdl_description = "",
                .rdl_answer = "",
                .token = true,
                .new_description = "",
                .description_after_usage_alone = "Guardi la targhetta, ma non sembra essere cambiato nulla.",
                .description_after_usage = "Hai inserito la targhetta nel calendario, ora le due cifre relative al giorno sono '14'.",
                .used_with = "calendario",
                .item_unlocked = {17, 17, 17},
            },           
        },
    },
};
